[workspace]
members = [
  "crates/postproject-cli",
  "crates/postproject-core",
  "crates/postproject-ffi",
  "crates/postproject-ffi-macros",
  "crates/postproject-media",
  "crates/postproject-storage-sqlite",
  "docs/examples/rust",
]
resolver = "3"
exclude = ["fuzz"]

[workspace.package]
version = "0.5.0-alpha.1"
edition = "2024"
rust-version = "1.85"
authors = ["PostProject contributors"]
repository = "https://github.com/postproject-org/postproject"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
