name: Downstream integration experiments

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  openassetio-manager:
    uses: postproject-org/postproject-openassetio/.github/workflows/ci.yml@main
    with:
      postproject_ref: ${{ github.sha }}

  openassetio-publishing:
    uses: postproject-org/postproject-openassetio-manager/.github/workflows/ci.yml@main
    with:
      postproject_ref: ${{ github.sha }}

  otio-openassetio:
    uses: postproject-org/postproject-otio-openassetio/.github/workflows/ci.yml@main
    with:
      postproject_ref: ${{ github.sha }}

  python-host:
    uses: postproject-org/postproject-python-host/.github/workflows/ci.yml@main
    with:
      postproject_ref: ${{ github.sha }}

  cpp-nle:
    uses: postproject-org/postproject-cpp-nle/.github/workflows/ci.yml@main
    with:
      postproject_ref: ${{ github.sha }}

  ardour:
    uses: postproject-org/postproject-ardour/.github/workflows/ci.yml@main
    with:
      postproject_ref: ${{ github.sha }}
